### PR TITLE
fix/270: undefined array offset

### LINKED ISSUE #270: Warning on displaying the page with Sophi Block
### Describe the bug

Happens on the very first page view after creation. Doesn't reproduce after page refresh

Warning: Trying to access array offset on value of type bool in /wp-content/plugins/sophi/includes/classes/SiteAutomation/Request.php on line 187

### Steps to Reproduce

1. Make a new install
2. Create a page with Sophi Block
3. View the page

### Screenshots, screen recording, code snippet

image

### Environment information

_No response_

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Sidsector9**
### Description of the Change

This PR checks if the value returned by transient is an array before accessing an offset.
Also replaces the deprecated filter `block_categories` with `block_categories_all`

Closes #270 

### Verification Process
1. Set `WP_DEBUG` and `WP_DEBUG_LOG` to true
2. Using `develop`, open a page that uses the Sophi Automation Block
3. Delete all transients (`wp transient delete --all`) and reload the page
4. Observe the error on the page
5. Checkout to branch `fix/270` and repeat (3)
6. Observe the error no longer exists on the page

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests passed.

### Changelog Entry
Fixed: replace deprecated `block_categories` filter with `block_categories_all`.
Fixed: fix warning shown due to access of undefined array

### Credits

Props @Sidsector9

### CODE REVIEW

File: includes/classes/SiteAutomation/Request.php [hunk 1]
```diff
@@ -176,7 +176,7 @@ private function set_status( $data ) {
 		);
 
 		if ( empty( $data['success'] ) ) {
-			$data['retry'] = $this->status['retry'] + 1;
+			$data['retry'] = is_array( $this->status ) ? $this->status['retry'] + 1 : 1;
```
Comment (cadic) [inline includes/classes/SiteAutomation/Request.php:179]: Despite the fact that checking $this->status is array will resolve the issue, but it still a potential warning if retry offset doesn't exist in the array. Could we check for `isset( $this->status['retry'] )`?

**Review by cadic — APPROVED** [review]
@Sidsector9 thank you for the fix. Loogs good, just a concern about the better approach to test array offset

File: includes/classes/SiteAutomation/Request.php (hunk 1 above)
Comment (Sidsector9) [reply includes/classes/SiteAutomation/Request.php:179]: @cadic I had similar thoughts, but checking the code I found `$this->status` is either set to a boolean or it is set to an array that always contains the `retry` key.

https://github.com/globeandmail/sophi-for-wordpress/blob/a4e6207727a7c82fc2b6d563f38f3da432bab406/includes/classes/SiteAutomation/Request.php#L169-L176

https://github.com/globeandmail/sophi-for-wordpress/blob/a4e6207727a7c82fc2b6d563f38f3da432bab406/includes/classes/SiteAutomation/Request.php#L184
