### PR TITLE
Fix: Add data attributes to site automation widgets

### LINKED ISSUE #63: Add data attributes to site automation widgets
In order to better capture widget groupings, we need to add a new data attribute to the main container that is used for the site automation widgets.

This attribute takes the form `data-sophi-feature="Widget Name"`

As an example:
```
<div class="wp-block-trending" data-sophi-feature="trending"> 
    <h3>Trending</h3>
    <ul>...</ul>
</div>
```

We currently have a widget name field on the Site Automation block, so I propose that name is what is used for this data attribute. From the examples we've been given, it looks like this name should be lowercase and spaces should be replaced with dashes, so might need to pass the widget name through sanitization to achieve this.

For direct integrations with `WP_Query`, this data attribute will need to be added on a site-by-site basis. We probably need to update documentation to mention this.

### PR DESCRIPTION
**Pull request by dinhtungdu**
See https://github.com/globeandmail/sophi-for-wordpress/issues/63#issuecomment-858381646

### CODE REVIEW

File: includes/blocks/site-automation-block/markup.php [hunk 1]
```diff
@@ -8,8 +8,11 @@
  * @var array $curated_posts Curated content from Sophi.
  */
 
+$page_name   = preg_replace( '/\s+/', '-', strtolower( $attributes['pageName'] ) ); // phpcs:ignore VariableAnalysis.CodeAnalysis.VariableAnalysis.UndefinedVariable
+$widget_name = preg_replace( '/\s+/', '-', strtolower( $attributes['widgetName'] ) ); // phpcs:ignore VariableAnalysis.CodeAnalysis.VariableAnalysis.UndefinedVariable
```
Comment (dkotter) [inline includes/blocks/site-automation-block/markup.php]: This is fine but you could also probably use `sanitize_title`, as I think that does what we want.

**Review by dkotter — APPROVED** [review]
