### PR TITLE
Prevent tracking a duplicate event

### LINKED ISSUE #269: duplicate call to sophi on post update
### Describe the bug

The CMS tracking function appears to fire twice when updating a post, we'll want to figure out why that's happening and trim that down so we only send a single update across to sophi when a post is updated.

### Steps to Reproduce

Install Sophi Debug Bar plugin, navigate to a sample post with the sophi block on it with a valid page/widget combo, update the post, see two update calls to sophi.

### Screenshots, screen recording, code snippet

_No response_

### Environment information

Verified on 10uplabs test site

### WordPress information

WP 5.9.3
Debug Bar 1.1.3
Sophi Debug Bar 0.1.0
Sophi 1.1.1-dev
Yoast 16.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by cadic**
### Description of the Change

This PR adds a transient with default TTL of 10 seconds for every new tracking event. If the transient exists and contain the same data, the tracking event is considered as duplicated call and will be skipped.

Closes #269 

### Verification Process

1. Install and activate: Sophi for WordPress, Debug Bar for Sophi and Yoast SEO plugins
2. Create new post or perform an update of an existing one.
3. Expected to see the single tracking request in Debug Bar 

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests passed.

### Changelog Entry

> Fixed - Prevent duplicate CMS publish/update event tracking.

### CODE REVIEW

**Comment by jeffpaul** [comment]
Curious if @peterwilsoncc has any insight on why this might be happening on the core side of things as well.

**Comment by peterwilsoncc** [comment]
@jeffpaul When the legacy meta boxes are enabled in the block editor (New Post > dot menu > preferences > panels > custom fields) core performs two updates each time a post is saved:
* one via the rest API
* one to update the legacy meta box data

Screen Shot 2022-10-07 at 9 16 40 am

For post updates, the full meta data isn't saved until the second (legacy meta boxes) request is completed.

It appears Yoast SEO force enables the legacy meta boxes either intentionally or unintentionally via their meta box config.

A check for `isset( $_GET['meta-box-loader'] ) && $_GET['meta-box-loader'] )` can be used to detect the second request for the legacy meta boxes.

File: includes/functions/content-sync.php [hunk 1]
```diff
@@ -311,3 +315,58 @@ function get_post_data( $post ) {
 	 */
 	return apply_filters( 'sophi_post_data', $data );
 }
+
+/**
+ * Check if the current data has been already tracked recently ans should be skipped.
```
Comment (peterwilsoncc) [inline includes/functions/content-sync.php]:
```suggestion
 * Check if the current data has been already tracked recently and should be skipped.
```

File: includes/functions/content-sync.php [hunk 2]
```diff
@@ -311,3 +315,58 @@ function get_post_data( $post ) {
...
+ *
+ * @since 1.3.0
+ *
+ * @param array $data Data being tracked
+ *
+ * @return boolean
+ */
+function maybe_skip_track_event( $data ) {
```
Comment (peterwilsoncc) [inline includes/functions/content-sync.php:328]: You may be able to simplify this to test if the request is coming from the legacy meta box loader:

```php
$skip = false;
if ( isset( $_GET['meta-box-loader'] ) && $_GET['meta-box-loader'] ) ) {
  $skip = true;
}
```

I haven't tested this so you might want to test a couple of things:
* it works as expected
* the code doesn't affect the classic editor

**Review by peterwilsoncc — COMMENTED** [review]
I've added a few notes inline.

If the `$data` been tracked includes the post's meta data, then it won't be saved in it's entirety until the second request runs to save the legacy meta boxes.

File: includes/functions/content-sync.php (hunk 2 above)
Comment (cadic) [reply includes/functions/content-sync.php:328]: Thank you for the idea! Added this logic in 4108ac8d

File: includes/functions/content-sync.php [hunk 3]
```diff
@@ -311,3 +315,60 @@ function get_post_data( $post ) {
...
+	$transient_hash = substr( wp_hash( wp_json_encode( $data ) ), 0, 8 );
+	$transient_name = 'sophi_tracking_request_' . $transient_hash;
+	$tracked_data   = get_transient( $transient_name );
+
+	if ( isset( $_GET['meta-box-loader'] ) && $_GET['meta-box-loader'] ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended, WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
+		// Skip if metabox is reloading.
+		$skip = true;
+	} elseif ( $tracked_data === $data ) {
+		// Skip duplicated track within last 10 seconds.
+		$skip = true;
```
Comment (peterwilsoncc) [inline includes/functions/content-sync.php]:
```suggestion

	// phpcs:ignore WordPress.Security.NonceVerification.Recommended, WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
	if ( isset( $_GET['meta-box-loader'] ) && $_GET['meta-box-loader'] ) {
		// Skip if metabox is reloading.
		$skip = true;
	} elseif ( get_transient( $transient_name ) === $data ) {
		// Skip duplicated track within last 10 seconds.
		$skip = true;
```

Two suggestions:
* phpcs:ignore can go on the line above, it makes it easier to read (if the comment is on it's own line, the next line is ignored)
* I moved `get_transient()` to the `elseif` so the DB query is only made when required

File: includes/functions/content-sync.php [hunk 4]
```diff
@@ -311,3 +315,60 @@ function get_post_data( $post ) {
...
+ *
+ * @param array $data Data being tracked
+ *
+ * @return boolean
+ */
+function maybe_skip_track_event( $data ) {
+	// Ignore modifiedAt.
+	unset( $data['modifiedAt'] );
+
+	$transient_hash = substr( wp_hash( wp_json_encode( $data ) ), 0, 8 );
```
Comment (peterwilsoncc) [inline includes/functions/content-sync.php]:
```suggestion
	$transient_hash = substr( md5( wp_json_encode( $data ) ), 0, 8 );
```

As this isn't used for cryptographic purposes, you can use an md5 instead of `wp_salt()`. By default the latter uses the AUTH salt which is only intended to be used for authentication purposes.

Transient names can be up to 172 characters long, so I don't think you need to truncate the hash but it's no big deal.

**Review by peterwilsoncc — COMMENTED** [review]
I've added a couple of notes inline. 

I think avoiding using the AUTH salt is probably the most important but even then, it's not major.

**Comment by jeffpaul** [comment]
@cadic would be great to get any updates from Peter's feedback handled this week so we could include this with Faisal's Overrides work in the 1.3.0 release; thanks!

**Comment by cadic** [comment]
@jeffpaul I've committed changes proposed by Peter and fixed unit test to pass the changes, but now SonarCloud fires a warning for md5() function, not sure if we should ignore it (or maybe revert both [ae27392](https://github.com/globeandmail/sophi-for-wordpress/pull/335/commits/ae273924734960de8e14994cf6f02c2ea28a1a57) and [ddae241](https://github.com/globeandmail/sophi-for-wordpress/pull/335/commits/ddae2415849b21fb09b4107c07c8bd6ed263fe1d))

**Comment by jeffpaul** [comment]
@peterwilsoncc do you have any input on those [SonarCloud items flagged](https://sonarcloud.io/project/security_hotspots?id=globeandmail_sophi-for-wordpress&pullRequest=335&resolved=false&types=SECURITY_HOTSPOT)?

**Comment by peterwilsoncc** [comment]
@jeffpaul @cadic The report can be ignored as a false positive as the hash is used to generate a unique key rather than for cryptographic purposes.
