### PR TITLE
SIT-3134: fix/232: Updated data type of keywords field to array.

### LINKED ISSUE #232: SIT-3134: Plugin update to correct the data type for keywords fields
### Describe the bug

From Vijay Jayaseelan:
>I am finding failed events coming from a client’s WP install for the following reason.
schema: content_update 2-0-3
>
>field: keywords
>
>error: received string instead of array or null. (please see image)
>
>steps to fix: allow an array of strings with min 0 and max 100 strings. Each string can have a min of 1 length and max of 128 length.
>
>Example 
Incorrect:
keywords: "covid"
Correct:
keywords: ["covid"]

### Steps to Reproduce

See more: https://voltron.atlassian.net/servicedesk/customer/portal/41/SIT-3134?created=true

### Screenshots, screen recording, code snippet

_No response_

### Environment information

_No response_

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by iamdharmesh**
### Description of the Change
As requested on #232, This PR updates the data type of the `keywords` field to array from string.

Closes #232 

### Verification Process
Verify that plugin sends an array of strings in the `keywords` field, further verification can be done on Sophi side logs.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry
Changed - The data type of keywords field to an array from string.

### Credits

Props @iamdharmesh @jeffpaul

### CODE REVIEW

**Comment by oscarssanchez** [comment]
Hi @iamdharmesh ,

Per the issue

File: includes/functions/content-sync.php [hunk 1]
```diff
@@ -198,7 +198,11 @@ function get_post_data( $post ) {
 			$canonical_url = $yoast_canonical;
 		}
 
-		$keywords = get_post_meta( $post->ID, '_yoast_wpseo_focuskw', true );
+		$yoast_focuskw = get_post_meta( $post->ID, '_yoast_wpseo_focuskw', true );
+		if ( ! empty( $yoast_focuskw ) ) {
```
Comment (oscarssanchez) [inline includes/functions/content-sync.php:202]: if `$yoast_focuskw` is empty, then `$keywords` will be still be an empty string. Do we want to change the initial data type as well?

File: includes/functions/content-sync.php [hunk 2]
```diff
@@ -198,7 +198,11 @@ function get_post_data( $post ) {
...
+			// Limit focus keyphrase to max length of 128.
+			$keywords = [ substr( $yoast_focuskw, 0, 128 ) ];
```
Comment (oscarssanchez) [inline includes/functions/content-sync.php:204]: Although we probably won't be sending anything over 100 strings as the array content, do we want to go ahead and implement that as well? Per requirement: 

`steps to fix: allow an array of strings with min 0 and max 100 strings.`

File: includes/functions/content-sync.php (hunk 1 above)
Comment (YMufleh) [reply includes/functions/content-sync.php:202]: Yes, if it's an empty string please have it as an empty array instead, or `null`

File: includes/functions/content-sync.php (hunk 2 above)
Comment (YMufleh) [reply includes/functions/content-sync.php:204]: Yes, 
Thank you

File: includes/functions/content-sync.php (hunk 1 above)
Comment (iamdharmesh) [reply includes/functions/content-sync.php:202]: We have `array_filter` on $data to remove all empty entries. So, in the case of empty `$yoast_focuskw`, the `keywords` field will be removed from $data and it will not be sent in request. As it is not going to send in a request, I think it's fine to keep it as it is. but it may create confusion for other devs too. So, I updated the initial value to `[]`.
Thanks

File: includes/functions/content-sync.php (hunk 2 above)
Comment (iamdharmesh) [reply includes/functions/content-sync.php:204]: @oscarssanchez `$yoast_focuskw` will be a single string. So, `$keywords` will be an array with 1 length always. However, the max length of the string can be up to 128, which I already implemented. Please let me know If I missed or misunderstood anything here. 
Thanks.

Comment (YMufleh) [reply includes/functions/content-sync.php:204]: Sonds good to me. 
How will this be populated if they are not using yoast?

**Review by YMufleh — APPROVED** [review]
LGTM! 
One question about functionality

File: includes/functions/content-sync.php (hunk 2 above)
Comment (iamdharmesh) [reply includes/functions/content-sync.php:204]: @YMufleh it will be only populated if Yoast is installed. If they are not using Yoast, `keywords` field will be not sent in the request. (note: `keywords` field is optional)

Comment (jeffpaul) [reply includes/functions/content-sync.php:204]: Noting here that WordPress, by default, does not provide `keywords` functionality and requires a plugin, like Yoast, to add on this SEO feature.  There are some other SEO plugins, but by default the plugin only supports Yoast.  If there are others that are determined to be in-use by other partners, then support for those SEO plugins can be added.

Comment (oscarssanchez) [reply includes/functions/content-sync.php:204]: @iamdharmesh , yes you are correct at this point we should not have more than 1 string, I was thinking more about future proofing, so something like `if (count($array) > 100) limit array` , but seems per @YMufleh we can leave this for now

Comment (oscarssanchez) [reply includes/functions/content-sync.php:204]: > l be only populated if Yoast is installed. If they are not using Yoast, `keywords` field will be n

Perhaps we could think using tags or something like that if no SEO plugin is installed @jeffpaul @YMufleh ? I'm not sure what effect would that have in Sophi though.

**Review by oscarssanchez — APPROVED** [review]

File: includes/functions/content-sync.php (hunk 2 above)
Comment (jeffpaul) [reply includes/functions/content-sync.php:204]: I believe tags are sent across in a different field/variable, right?  Just like categories?

Comment (jeffpaul) [reply includes/functions/content-sync.php:204]: See categories: https://github.com/globeandmail/sophi-for-wordpress/blob/47fbb181999890297e3cad5594832c0443d5dd14/includes/functions/content-sync.php#L220
and tags: https://github.com/globeandmail/sophi-for-wordpress/blob/47fbb181999890297e3cad5594832c0443d5dd14/includes/functions/content-sync.php#L222

...right?

**Comment by jeffpaul** [comment]
Given both @YMufleh and @oscarssanchez approved, I'm going to merge in so we can get this to our test site for further validation before a plugin minor release.
