### PR TITLE
Fix: Unconfigured plugin loads snowplow analytics

### LINKED ISSUE #58: Unconfigured plugin loads snowplow analytics
When activating the plugin, it will try to load https://https//collector.sophi.io/com.snowplowanalytics.snowplow/tp2 even if the plugin has not been configured yet (also note the incorrect address).

Ideally the plugin would do nothing unless properly configured.

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Description of the Change
This PR fixes #58 by ensuring all required settings are set before enabling plugin's functionalities. This PR also add new notice asking users to setup the credentials after activating the plugin.

### Verification Process
1. Activate Sophi on a new site.
2. See new notice asking user setup the credentials.
3. Setup the credentials.
4. Go back to the plugins page. See no notice.

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/globeandmail/sophi-for-wordpress/blob/develop/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues
Closes #58

### CODE REVIEW

File: includes/functions/utils.php [hunk 1]
```diff
@@ -187,3 +189,23 @@ function get_supported_post_types() {
 	 */
 	return apply_filters( 'sophi_supported_post_types', [ 'post', 'page' ] );
 }
+
+function is_configured() {
```
Comment (dkotter) [inline includes/functions/utils.php:198]: Should add a dockblock to this function

Comment (dinhtungdu) [reply includes/functions/utils.php:198]: Added the docblock

**Comment by dinhtungdu** [comment]
@dkotter I added the docblock, please review this again!

**Review by dkotter — APPROVED** [review]
